name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-coverage:
    name: Coverage
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/insightsengineering/rstudio_4.1.1_bioc_3.13:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: install.packages("covr", repos="http://cran.rstudio.com/")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::package_coverage()
        shell: Rscript {0}
